AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
  - 'db/**/*'
  - 'bin/**/*'
  - 'vendor/**/*'
require:
  - rubocop-rspec
Style/Documentation: 
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 100
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExpectActual:
  Enabled: false
