AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
  - 'db/**/*'
  - 'bin/**/*'
require:
  - rubocop-rspec
Style/Documentation: 
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 50
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExpectActual:
  Enabled: false
